### ISSUE TITLE
mac version says it is not safe and cannot be open

### ISSUE THREAD

**Issue by insign** [AvainApp/avain-desktop#22]

**Comment by pakastin** [comment]
Thanks for the info, will fix! 👍

**Comment by pakastin** [comment]
Let me know if this helps: https://github.com/AvainApp/avain-desktop/releases/tag/v0.7.0

**Comment by pakastin** [comment]
You could also try following if not:

- Move to applications folder
- Right click the app
- Choose "Open" or "Open anyway"

You can also build from the source yourself if you want:

```
npm i
npm run build
```

–>

`dist/Avain-0.7.0-arm64.dmg`
